### ISSUE TITLE
Add PDF output to m3d

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-m3d#7]
Concern has been raised about the PDF output of the HTML, done via Print to HTML, looking bad. Automating PDF output via puppeteer tends to look a lot better than going via browser, so am adding PDF output to this gem.

**Comment by opoudjis** [comment]
[rfc6350.pdf](https://github.com/riboseinc/metanorma-m3d/files/2342082/rfc6350.pdf)

This is the output now, and it looks fine to me. If there are things to be changed, I will need specifics.

**Comment by ronaldtse** [comment]
This looks so much better! Actually it looks great.

Some remaining issues:

1. M3AAWG logo is squished sideways
2. The "link" icons next to section headers should not be shown
3. Missing ToC
4. Title page copyright year 2018, at the end colophon says 2017.
5. There are a number of spurious elements on the title page:

```
Updated August 2011, Version draft (should be something here?) 
(what's this?) TC ISO/TC 154PROCESSES, DATA ELEMENTS AND DOCUMENTS IN COMMERCE, INDUSTRY AND ADMINISTRATION
(what's this?) RIBOSE REPORT
(what's this? is this in contrast with DRAFT?) PUBLISHED
```
